### ISSUE TITLE
Does not support MultiGPU training

### ISSUE THREAD

**Issue by qizhust** [vacancy/NSCL-PyTorch-Release#14]
Hi, an AssertionError 
```
assert len(progs) == len(batch_features)
```
appears when 
```
args.gpu_parallel=True
```
did you meet this error?

**Comment by vacancy** [comment]
Sorry maybe I didn't state clearly in the README file, this code does not support multi GPU training -- actually, using DataParallel won't increase the speed as the bottleneck is the dense CPU operations in program execution.

Using multiprocessing based data parallelism might help, but I haven't tried that.

**Comment by qizhust** [comment]
Yep, I see. Thanks for your reply :)
