### ISSUE TITLE
Where can I find the images in questions.json for validation?

### ISSUE THREAD

**Issue by aishniparab** [vacancy/NSCL-PyTorch-Release#20]
For the validation, questions.json file is provided. It contains 15,000 unique images with filenames ranging from CLEVR_val_000000.png to CLEVR_val_014999.png. However, the original CLEVR dataset has two validation splits, split A has filenames going from CLEVR_ValA_00000.png to CLEVR_ValA_014999.png, whereas split B has filenames going from CLEVR_ValB_000000.png to CLEVR_ValB_000000.png. The images in each split are different, so which filenames is questions.json referring to?

**Comment by vacancy** [comment]
I guess you were using the CLEVR-CoGenT instead of the actual CLEVR?
