### ISSUE TITLE
_use_shared_memory - PyTorch 1.1

### ISSUE THREAD

**Issue by bergen** [vacancy/NSCL-PyTorch-Release#4]
The following error appears with PyTorch 1.1: 
>  File "Jacinle/jactorch/data/collate.py", line 149, in _stack
>     if torchdl._use_shared_memory:
> AttributeError: module 'torch.utils.data.dataloader' has no attribute '_use_shared_memory'

dataloader in 1.1 does not have an attribute '_use_shared_memory', see [here](https://pytorch.org/docs/stable/_modules/torch/utils/data/dataloader.html#DataLoader).

**Comment by vacancy** [comment]
Fixed in the latest Jacinle. Thanks for reporting.
