### ISSUE TITLE
Error coming from Jacinle

### ISSUE THREAD

**Issue by chrisrytting** [vacancy/NSCL-PyTorch-Release#7]
I've followed all the instructions in the README.md. However, when I get to running the command `jac-crun <gpu_id> scripts/trainval.py --desc experiments/clevr/desc_nscl_derender.py --training-target derender --curriculum all --dataset clevr --data-dir <data_dir>/clevr/train --batch-size 32 --epoch 100 --validation-interval 5 --save-interval 5 --data-split 0.95`, I get this error 

```
(nscl) crytting@hatch:~$ jac-crun GPU-0ff7a712-8a42-af6d-7f21-17147fda6a7c --desc experiments/clevr/desc_nscl_derender.py --training-target derender --curriculum all --dataset clevr --data-dir ./clevr/train --batch-size 32 --epoch 100 --validation-interval 5 --save-interval 5 --data-split 0.95
11 09:56:09 Loading jacinle config: /home/crytting/Jacinle/jacinle.yml.
11 09:56:09 Loading vendor: ReservoirSample-PyTorch.
11 09:56:09 Loading vendor: AdvancedIndexing-PyTorch.
11 09:56:09 Loading vendor: SynchronizedBatchNorm-PyTorch.
11 09:56:09 Loading vendor: PreciseRoIPooling-PyTorch.
11 09:56:09 Loading vendor: SceneGraphParser.
/home/crytting/Jacinle/bin/jac-run: line 10: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```

The line 10 that it references is

```
exec "$@"
```

from the mentioned file `/home/crytting/Jacinle/bin/jac-run`. Any ideas on how to fix?

**Comment by eddjou** [comment]
I think you just forgot typing in
`scripts/trainval.py`
